### ISSUE TITLE
Bug with not-perf(local_unwinding)

### ISSUE THREAD

**Issue by nuttert** [koute/bytehound#101]
```
thread '<unnamed>' panicked at 'index out of bounds: the len is 256 but the index is 18446744073709551615', /home/user/.cargo/git/checkouts/not-perf-af1a46759dd83df9/911723c/nwind/src/local_unwinding.rs:455:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

I got the error(unfortunately I can't attach the code), there is some problem with index calculations.

**Comment by nuttert** [comment]
The problem in the commit `Update nwind to 20e4ddc`

**Comment by nuttert** [comment]
Hey guys, is anyone alive? 😅
@koute, or may be @CsatariGergely ...

**Comment by preslavle** [comment]
I am hitting this too. Running on AWS Graviton
```thread '<unnamed>' panicked at 'index out of bounds: the len is 256 but the index is 18446744073709551615', /cache/cargo/git/checkouts/not-perf-af1a46759dd83df9/911723c/nwind/src/local_unwinding.rs:455:26
stack backtrace:
   0:     0xffffafd10368 - std::backtrace_rs::backtrace::libunwind::trace::h14c7f950a9fbd0fb
                               at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0xffffafd10368 - std::backtrace_rs::backtrace::trace_unsynchronized::h9f22adb7e822c7cc
                               at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0xffffafd10368 - std::sys_common::backtrace::_print_fmt::he29650cef1baf79b
                               at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/sys_common/backtrace.rs:66:5
   3:     0xffffafd10368 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h86dca612c56e965d
                               at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/sys_common/backtrace.rs:45:22
   4:     0xffffafcc85f8 - core::fmt::write::hf53eafa31f33ff33
                               at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/core/src/fmt/mod.rs:1209:17
   5:     0xffffafcf4290 - std::io::Write::write_fmt::h3d0aa180e3a1924e
                               at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/io/mod.rs:1680:15
   6:     0xffffafd10e6c - std::sys_common::backtrace::_print::h65ae785b2839811f
                               at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/sys_common/backtrace.rs:48:5
   7:     0xffffafd10e6c - std::sys_common::backtrace::print::h5094d9b652e55b51
                               at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/sys_common/backtrace.rs:35:9
   8:     0xffffafd10e6c - std::panicking::default_hook::{{closure}}::h9cf17da72539362b
                               at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/panicking.rs:267:22
   9:     0xffffafd114d4 - std::panicking::default_hook::h60aadb13955e21f5
                               at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/panicking.rs:286:9
  10:     0xffffafd114d4 - std::panicking::rust_panic_with_hook::hcb6c786f4d42ec43
                               at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/panicking.rs:688:13
  11:     0xffffafd111f4 - std::panicking::begin_panic_handler::{{closure}}::ha5a0a21a8d71d9aa
                               at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/panicking.rs:579:13
  12:     0xffffafd11168 - std::sys_common::backtrace::__rust_end_short_backtrace::h259a79fe3a411d52
                               at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/sys_common/backtrace.rs:138:18
  13:     0xffffafd11144 - rust_begin_unwind
                               at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/panicking.rs:575:5
  14:     0xffffafc6dfec - core::panicking::panic_fmt::h46030d397fa08c3c
                               at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/core/src/panicking.rs:65:14
  15:     0xffffafc6e038 - core::panicking::panic_bounds_check::h403420092da262ff
                               at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/core/src/panicking.rs:151:5
  16:     0xffffafc98d90 - nwind::local_unwinding::ShadowStack::push::hecf859428c553613
                               at /cache/cargo/git/checkouts/not-perf-af1a46759dd83df9/911723c/nwind/src/local_unwinding.rs:455:26
  17:     0xffffafc98d90 - nwind::local_unwinding::LocalAddressSpace::unwind_through_fresh_frames::hef42f2bd7a59ce74
                               at /convex/bytehound/preload/src/unwind.rs:393:31
  18:     0xffffafc98d90 - bytehound::unwind::grab_with_unwind_state::hebf000e283895c43
                               at /convex/bytehound/preload/src/unwind.rs:393:31
  19:     0xffffafd79df4 - nwind_ret_trampoline_start
                               at /cache/cargo/git/checkouts/not-perf-af1a46759dd83df9/911723c/nwind/src/arch/aarch64_trampoline.s:15
  20:                0x0 - <unknown>
```

@nuttert did you find a workaround? Do versions prior to the problem commit above work? Seems pretty old commit to me.

**Comment by angelskieglazki** [comment]
Hi!
Any news? I have similar error...
```
thread '<unnamed>' panicked at 'index out of bounds: the len is 256 but the index is 18446744073709551615', /home/max/.cargo/git/checkouts/not-perf-af1a46759dd83df9/911723c/nwind/src/local_unwinding.rs:455:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/core/src/panicking.rs:65:14
   2: core::panicking::panic_bounds_check
             at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/core/src/panicking.rs:151:5
   3: nwind::local_unwinding::ShadowStack::push
             at /home/max/.cargo/git/checkouts/not-perf-af1a46759dd83df9/911723c/nwind/src/local_unwinding.rs:455:26
   4: nwind::local_unwinding::LocalAddressSpace::unwind_through_fresh_frames
             at /home/max/projects/misc/bytehound/preload/src/unwind.rs:393:31
   5: bytehound::unwind::grab_with_unwind_state
             at /home/max/projects/misc/bytehound/preload/src/unwind.rs:393:31
   6: nwind_ret_trampoline_start
             at /home/max/.cargo/git/checkouts/not-perf-af1a46759dd83df9/911723c/nwind/src/arch/amd64_trampoline.s:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Dump path: ./mini_dumps/f203dca1-1e2d-444c-9ef9d59a-d2e6e866.dmp
Aborted
```
