### ISSUE TITLE
build bytehound-cli error

### ISSUE THREAD

**Issue by frankleaf** [koute/bytehound#111]
ERROR: --version is not COMMAND nor fully qualified CLASSNAME.
  ERROR: install is not COMMAND nor fully qualified CLASSNAME.
  thread 'main' panicked at 'Failed to install the dependencies for the WebUI; child process exited with error code Some(1)! You might want to try to run 'rm -Rf ~/.cache/yarn' and try again.', server-core/build.rs:103:21
  stack backtrace:
     0:     0x5619cdfec7b0 - std::backtrace_rs::backtrace::libunwind::trace::h3e77d209dbe25d44
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     1:     0x5619cdfec7b0 - std::backtrace_rs::backtrace::trace_unsynchronized::h7b51789e46abdb59
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x5619cdfec7b0 - std::sys_common::backtrace::_print_fmt::h29c0cf5b16446d6c
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/sys_common/backtrace.rs:66:5
     3:     0x5619cdfec7b0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he2b16940c12b0a1c
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/sys_common/backtrace.rs:45:22
     4:     0x5619ce00aa4e - core::fmt::write::h87402e19ed548a07
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/core/src/fmt/mod.rs:1209:17
     5:     0x5619cdfe9b55 - std::io::Write::write_fmt::h4871973da13e833c
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/io/mod.rs:1680:15
     6:     0x5619cdfede43 - std::sys_common::backtrace::_print::hfbc51fe555810664
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/sys_common/backtrace.rs:48:5
     7:     0x5619cdfede43 - std::sys_common::backtrace::print::h51f4b0d418249766
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/sys_common/backtrace.rs:35:9
     8:     0x5619cdfede43 - std::panicking::default_hook::{{closure}}::h9a4f152744c1006f
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/panicking.rs:267:22
     9:     0x5619cdfedb1a - std::panicking::default_hook::h342cf3f3815b35a4
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/panicking.rs:286:9
    10:     0x5619cdfee648 - std::panicking::rust_panic_with_hook::hf0aa4307dfa3e7bd
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/panicking.rs:688:13
    11:     0x5619cdfee3e7 - std::panicking::begin_panic_handler::{{closure}}::h75ee99c9aa66f273
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/panicking.rs:579:13
    12:     0x5619cdfecc5c - std::sys_common::backtrace::__rust_end_short_backtrace::h4b65f67219b426e3
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/sys_common/backtrace.rs:138:18
    13:     0x5619cdfee102 - rust_begin_unwind
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/panicking.rs:575:5
    14:     0x5619cdfb5133 - core::panicking::panic_fmt::hcf2951a500cefd44
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/core/src/panicking.rs:65:14
    15:     0x5619cdfc2dad - build_script_build::main::{{closure}}::h2d428e2aace3fe31
                                 at /root/bytehound-master/server-core/build.rs:103:21
    16:     0x5619cdfb9cdd - semalock::Semalock::with::{{closure}}::h689b81c30b9dd2bb
                                 at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/semalock-0.2.0/src/lib.rs:99:30
    17:     0x5619cdfb855c - core::result::Result<T,E>::and_then::ha746535567eb6b80
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/core/src/result.rs:1372:22
    18:     0x5619cdfb9c63 - semalock::Semalock::with::h85820a6a34935818
                                 at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/semalock-0.2.0/src/lib.rs:96:9
    19:     0x5619cdfc275b - build_script_build::main::hf4d3804e4d1efcdf
                                 at /root/bytehound-master/server-core/build.rs:74:5
    20:     0x5619cdfbf97b - core::ops::function::FnOnce::call_once::hc6f31932ac5b5e94
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/core/src/ops/function.rs:251:5
    21:     0x5619cdfba9be - std::sys_common::backtrace::__rust_begin_short_backtrace::hf958695a7907fc63
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/sys_common/backtrace.rs:122:18
    22:     0x5619cdfc4a01 - std::rt::lang_start::{{closure}}::h863e9e75bdfd6b1e
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/rt.rs:166:18
    23:     0x5619cdfe683b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h245dd2efb995b37c
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/core/src/ops/function.rs:286:13
    24:     0x5619cdfe683b - std::panicking::try::do_call::he4e28ab86720b160
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/panicking.rs:483:40
    25:     0x5619cdfe683b - std::panicking::try::haa8f2059d379c88d
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/panicking.rs:447:19
    26:     0x5619cdfe683b - std::panic::catch_unwind::h7fd95a48f6d0e6c6
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/panic.rs:137:14
    27:     0x5619cdfe683b - std::rt::lang_start_internal::{{closure}}::h3e33e3e6adc9feb8
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/rt.rs:148:48
    28:     0x5619cdfe683b - std::panicking::try::do_call::he992b4b46fe1672b
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/panicking.rs:483:40
    29:     0x5619cdfe683b - std::panicking::try::hff7554696755340d
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/panicking.rs:447:19
    30:     0x5619cdfe683b - std::panic::catch_unwind::h8cc021a561296d2c
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/panic.rs:137:14
    31:     0x5619cdfe683b - std::rt::lang_start_internal::ha594ff75fed353d6
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/rt.rs:148:20
    32:     0x5619cdfc49da - std::rt::lang_start::h913a72480e73373e
                                 at /rustc/c0983a9aac889d16722a12602ac678051e62c3fb/library/std/src/rt.rs:165:17
    33:     0x5619cdfc4191 - main
    34:     0x7f0d669d6555 - __libc_start_main
    35:     0x5619cdfb5472 - <unknown>
    36:                0x0 - <unknown>

**Comment by zhwllq** [comment]
Hi, were you able to solve this issue？ I've met the question as you too
