### ISSUE TITLE
Feature request: check `yarn`'s version and return an error with a nice message when it is too old

### ISSUE THREAD

**Issue by s-d-m** [koute/bytehound#59]
Hi,

On some systems (like debian SID), the packaged yarn is too old and compilation fails with the following error
```
  --- stdout
  0.32+git

  --- stderr
  ERROR: [Errno 2] No such file or directory: 'install'
  thread 'main' panicked at 'Failed to install the dependencies for the WebUI; child process exited with error code Some(1)! You might want to try to run 'rm -Rf ~/.cache/yarn' and try again.', server-core/build.rs:85:21
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/0d1754e8bf6942b4c1d24d7c923438782129ba5a/library/std/src/panicking.rs:498:5
     1: core::panicking::panic_fmt
               at /rustc/0d1754e8bf6942b4c1d24d7c923438782129ba5a/library/core/src/panicking.rs:106:14
     2: build_script_build::main::{{closure}}
               at ./build.rs:85:21
     3: semalock::Semalock::with::{{closure}}
               at /home/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/semalock-0.2.0/src/lib.rs:99:30
     4: core::result::Result<T,E>::and_then
               at /rustc/0d1754e8bf6942b4c1d24d7c923438782129ba5a/library/core/src/result.rs:966:22
     5: semalock::Semalock::with
               at /home/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/semalock-0.2.0/src/lib.rs:96:9
     6: build_script_build::main
               at ./build.rs:62:5
     7: core::ops::function::FnOnce::call_once
               at /rustc/0d1754e8bf6942b4c1d24d7c923438782129ba5a/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
The solution is to use yarn installed from npm and not from the system's repositories. Could we have a version check and a message telling the using to install yarn from https://classic.yarnpkg.com/en/ ?

**Comment by koute** [comment]
Newest version should now build properly on ancient distros.
