### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by krzysiek6d** [koute/bytehound#97]
Hi

We have troubles when analysing gathered data. Gathered data is about 9GB.
We tried to squeeze the data but it failed. Then we tried to load big data and it failed as well
```
./bytehound strip --output X Y.dat
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /tmp/koute/memory-profiler/cli-core/src/squeeze.rs:217:100
none: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

when loading big data:
```
./bytehound server Y.dat
[2022-12-01T15:11:46Z INFO  server_core] Trying to load "Y.dat"...
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli-core/src/loader.rs:864:68
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted
```

Did you encounter such problem? Do you know how we should proceed with that?

**Comment by krzysiek6d** [comment]
lines 862:865 of loader.rs
```
            Event::AllocEx { id, timestamp, allocation: AllocBody { pointer, size, backtrace, thread, flags, extra_usable_space, preceding_free_space } } => {
                let timestamp = self.shift_timestamp( timestamp );
                let backtrace = self.lookup_backtrace( backtrace ).unwrap();
                self.handle_alloc( id, timestamp, pointer, size, backtrace, thread, flags, extra_usable_space, preceding_free_space );
            },
```

lines 212:233 of squeeze.rs
```
                Event::AllocEx { mut allocation, timestamp, id, .. } => {
                    current_timestamp = std::cmp::max( timestamp, current_timestamp );

                    let usable_size = allocation.size + allocation.extra_usable_space as u64;
                    {
                        allocation.backtrace = backtrace_map.get( &allocation.backtrace ).copied().unwrap();
                        let stats = stats_by_backtrace.entry( allocation.backtrace ).or_insert_with( || {
                            GroupStatistics {
                                first_allocation: timestamp,
                                last_allocation: timestamp,
                                free_count: 0,
                                free_size: 0,
                                min_size: usable_size,
                                max_size: usable_size
                            }
                        });

                        stats.first_allocation = min( stats.first_allocation, timestamp );
                        stats.last_allocation = max( stats.last_allocation, timestamp );
                        stats.min_size = min( stats.min_size, usable_size );
                        stats.max_size = min( stats.max_size, usable_size );
                    }
```

**Comment by krzysiek6d** [comment]
on current version (acce3bce127705ea8c840767ed351229a3c2738c) of bytehound output is as below:
```
./bytehound strip --output stripped.dat  unstripped.dat 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/xxx/Documents/code/koute_bytehound/new/bytehound/cli-core/src/squeeze.rs:217:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: IOT instruction (core dumped)  ~/Documents/code/koute_bytehound/new/bytehound/target/release/bytehound strip
```

```
./bytehound server  unstripped.dat
[2022-12-01T17:26:25Z INFO  server_core] Trying to load "/home/xxx/unstripped.dat"...
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli-core/src/loader.rs:1138:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: IOT instruction (core dumped)  ~/Documents/code/koute_bytehound/new/bytehound/target/release/bytehound serve
```

**Comment by koute** [comment]
Looks like there's some issue with backtrace IDs; an allocation has a backtrace ID for a backtrace which doesn't exist, which should never happen.

With which exact version did you gather the data and on which architecture?

**Comment by olorin37** [comment]
I suppose it was 0.8.0, @krzysiek6d please confirm.

**Comment by krzysiek6d** [comment]
Hi, seems that you're right, it's quite old - I'm not sure if our CI scripts take something more recent, but even if they take it's older than 8months.

Last commits are:

[Change default backtrace cache sizes and make them separately configurable]
(b04c8e1fe3245a5658b84c4f0e1329bf24f9cec8)
<koute>  authored 1 year ago

[Bump version to 0.8.0]
(0e13357c3c6e330b39e53b2aaa414b95e29488b1)
<koute> authored 1 year ago

Architecture is mips64


Anyway, after making such changes:
```
diff --git a/cli-core/src/loader.rs b/cli-core/src/loader.rs
index 79ac1cd..1758f0f 100644
--- a/cli-core/src/loader.rs
+++ b/cli-core/src/loader.rs
@@ -1135,8 +1135,13 @@ impl Loader {
             },
             Event::AllocEx { id, timestamp, allocation: AllocBody { pointer, size, backtrace, thread, flags, extra_usable_space, preceding_free_space: _ } } => {
                 let timestamp = self.shift_timestamp( timestamp );
-                let backtrace = self.lookup_backtrace( backtrace ).unwrap();
-                self.handle_alloc( id, timestamp, pointer, size, backtrace, thread, flags, extra_usable_space );
+                let bt = self.lookup_backtrace( backtrace );
+                if bt.is_some()
+                {
+                       let backtrace = bt.unwrap();
+                       self.handle_alloc( id, timestamp, pointer, size, backtrace, thread, flags, extra_usable_space );
+                }
+               
             },
             Event::Realloc { timestamp, old_pointer, allocation: AllocBody { pointer, size, backtrace, thread, flags, extra_usable_space, preceding_free_space: _ } } => {
                 let timestamp = self.shift_timestamp( timestamp );
```
I was able to get some useful information with generated graph. If you have some ideas what could get wrong then we'd be happy to hear what we should do/fix to avoid such problems

**Comment by koute** [comment]
Yeah, that workaround should work, although it will then skip some of the allocations.

It is possible that the version you're using had a bug that I've since then fixed; at this point I don't really remember.

You should probably try to switch to the newest version. (Although you might want to disable some of the new extra features which you might not need and which might add some extra CPU and memory overhead; e.g. set `MEMORY_PROFILER_GATHER_MAPS` and `MEMORY_PROFILER_GRAB_BACKTRACES_ON_FREE` to `0` if it ends up being too slow with these enabled).

**Comment by krzysiek6d** [comment]
I'll try to ask for update and thanks for the flags information. 

Let's close this thread, if the issue will be present on newer version then I'll open the ticket again ;)
Thank you
